export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

export const CREATE_APPLICATION = 'CREATE_APPLICATION';
export const GET_APPLICATIONS = 'GET_APPLICATIONS';
export const GET_APPLICATION = 'GET_APPLICATION';
export const UPDATE_APPLICATION = 'UPDATE_APPLICATION';
export const SUBMIT_APPLICATION = 'SUBMIT_APPLICATION';
export const START_REVIEW = 'START_REVIEW';
export const REJECT_APPLICATION = 'REJECT_APPLICATION';
export const APPROVE_APPLICATION = 'APPROVE_APPLICATION';
export const REQUEST_MORE_APPLICATION = 'REQUEST_MORE_APPLICATION';
export const COMPLETE_REVIEW_APPLICATION = 'COMPLETE_REVIEW_APPLICATION';

export const CREATE_DOCUMENT = 'CREATE_DOCUMENT';
export const GET_DOCUMENTS = 'GET_DOCUMENTS';
export const GET_DOCUMENT = 'GET_DOCUMENT';
export const UPDATE_DOCUMENT = 'UPDATE_DOCUMENT';
export const DOWNLOAD_DOCUMENT = 'DOWNLOAD_DOCUMENT';

export const CREATE_USER = 'CREATE_USER';
export const GET_USERS = 'GET_USERS';
export const GET_USER = 'GET_USER';
export const UPDATE_USER = 'UPDATE_USER';

export const CREATE_AUDIT_LOG = 'CREATE_AUDIT_LOG';
export const GET_AUDIT_LOGS = 'GET_AUDIT_LOGS';
export const GET_AUDIT_LOG = 'GET_AUDIT_LOG';
export const UPDATE_AUDIT_LOG = 'UPDATE_AUDIT_LOG';
